language: node_js
node_js:
 - "11.6.0"
branches:
  only:
  - staging
  - master
deploy:
  - provider: elasticbeanstalk
    access_key_id: abc
    secret_access_key:
      secure: abc
    region: "ap-south-1"
    app: "next-app"
    env: "next-app-staging"
    bucket_name: abc
    on:
      branch: "staging"

  - provider: elasticbeanstalk
    access_key_id: abc
    secret_access_key:
      secure: abc
    region: "ap-south-1"
    app: "next-app"
    env: "next-app-production"
    bucket_name: abc
    on:
      branch: "master"

after_deploy:
  - echo "Application Deployed!"
